

name: delete workflow

on:
  push:
    branches:
        - main
env:
  GH_TOKEN: ${{ github.token }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:    
    runs-on: ubuntu-latest
    steps:   
    - name: Send greeting
      run: |
          apt install gh \
          gh workflow list
           
