

name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string
      name2:
        description: 'enter workflow id to delete'
        required: true
        type: string
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  greet:
    
    runs-on: ubuntu-latest

    
    steps:
   
    - name: Send greeting
      run: curl -X DELETE https://api.github.com/repos/alimelus/github_actions/actions/runs/5857540878
           
