

name: delete workflow

on:
  push:
    branches:
        - main
env:
  GH_TOKEN: ${{ github.token }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:    
    runs-on: ubuntu-latest
    steps:   
    - name: Send greeting
      run: |
          OWNER=alimelus
          REPO=github_actions 
        
          curl -L \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer <YOUR-TOKEN>" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/OWNER/REPO/actions/workflows
           
