

name: delete workflow

on:
  push:
    branches:
        - main
     
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  greet:
    
    runs-on: ubuntu-latest

    
    steps:
   
    - name: Send greeting
      run: 
          org=alimelus
          repo=github_actions   
        
          workflow_ids=( $(gh api repos/$org/$repo/actions/workflows --paginate | jq '.workflows[] | select(.["state"] | contains("disabled_manually")) | .id') )     
          for workflow_id in "${workflow_ids[@]}"
          do
            echo "Listing runs for the workflow ID $workflow_id"
            run_ids=( $(gh api repos/$org/$repo/actions/workflows/$workflow_id/runs --paginate | jq '.workflow_runs[].id') )
            for run_id in "${run_ids[@]}"
            do
              echo "Deleting Run ID $run_id"
              gh api repos/$org/$repo/actions/runs/$run_id -X DELETE >/dev/null
            done
          done
           
